### ISSUE TITLE
Make iframe of dynamic map responsive

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/simple_gmap#1]
I'm wondering with this module how easy it would be to embed some responsive CSS for the iframe.  I didn't really have much luck with the width and height as it didn't seem to recognise vw as a unit, pixels are no good for responsive and percent, while it works for width is problematic for the height.

I applied this CSS (Source: https://www.w3schools.com/howto/howto_css_responsive_iframes.asp) to the containing div and the iframe:

```css
.node-location .field-item {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

.node-location iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

I'm happy to add this to my site CSS, but for others, it may be better if we can integrate this.  I'm not sure of the best way to add CSS to a module like this, but I'm happy to have a go with a bit of a steer.
